"""A7 — `fleet infer` reproduces the six-server least-privilege table.

The public demo (`demo/README.md`, Part B) presents a least-privilege table:
each server is pinned to exactly the capability classes its declared tool
surface implies, deny-by-default everywhere else. That table is regenerated by
`mcp-contract fleet infer` — the batch inference verb — not by a hand-rolled
shell loop. This test drives `fleet infer` over the six bundled fixture
manifests and asserts the resulting per-server classes, so the documented
table can never silently drift from what PIE+fleet actually produce.

Everything runs through `mcp_contract.cli.main` (no subprocess); policies are
written to tmp_path and read back with `load_policy`.
"""
from __future__ import annotations

import json
from pathlib import Path

from mcp_contract.cli import main
from mcp_contract.policy import load_policy

FIXTURES = Path(__file__).resolve().parent / "fixtures"
MANIFESTS = FIXTURES / "manifests"

# server -> {capability id: (status, expected values | None)}.
# None values = "do not assert scope" (denied classes carry no values).
# Mirrors the least-privilege classes the rule-based PIE derives from each
# fixture's declared tool surface (DESIGN.md "Module A"): a value is asserted
# only where the class is granted (inferred) or flagged (needs_review) with a
# concrete scope.
EXPECTED: dict[str, dict[str, tuple[str, set[str] | None]]] = {
    # descriptions name api.github.com -> net inferred; GITHUB_TOKEN -> env review
    "github": {
        "net.http": ("inferred", {"api.github.com"}),
        "fs.read": ("denied", None),
        "fs.write": ("denied", None),
        "proc.exec": ("denied", None),
        "env": ("needs_review", {"GITHUB_TOKEN"}),
    },
    # read/write/list a path param, no literal -> fs class, scope unknown
    "filesystem": {
        "net.http": ("denied", None),
        "fs.read": ("needs_review", set()),
        "fs.write": ("needs_review", set()),
        "proc.exec": ("denied", None),
        "env": ("denied", None),
    },
    # fetch(url): the endpoint is a runtime param -> net needs_review, "*" scope
    "fetch": {
        "net.http": ("needs_review", {"*"}),
        "fs.read": ("denied", None),
        "fs.write": ("denied", None),
        "proc.exec": ("denied", None),
        "env": ("denied", None),
    },
    # run_command -> proc.exec, never auto-inferred (a human must approve exec)
    "shell": {
        "net.http": ("denied", None),
        "fs.read": ("denied", None),
        "fs.write": ("denied", None),
        "proc.exec": ("needs_review", None),
        "env": ("denied", None),
    },
    # net (slack.com) + SLACK_BOT_TOKEN env
    "slack": {
        "net.http": ("inferred", {"slack.com"}),
        "fs.read": ("denied", None),
        "fs.write": ("denied", None),
        "proc.exec": ("denied", None),
        "env": ("needs_review", {"SLACK_BOT_TOKEN"}),
    },
    # query/execute against a /data db file -> fs, with a literal /data prefix
    "sqlite": {
        "net.http": ("denied", None),
        "fs.read": ("needs_review", {"/data"}),
        "fs.write": ("inferred", {"/data"}),
        "proc.exec": ("denied", None),
        "env": ("denied", None),
    },
}

ALL_CLASSES = {"net.http", "fs.read", "fs.write", "proc.exec", "env"}


def test_fleet_infer_reproduces_six_server_table(tmp_path, capsys):
    outdir = tmp_path / "policies"
    rc = main(["fleet", "infer", str(MANIFESTS), "-o", str(outdir)])
    out, _ = capsys.readouterr()
    assert rc == 0

    # one aggregate FleetReport, one run per fixture server
    report = json.loads(out)
    assert {run["server_id"] for run in report["runs"]} == set(EXPECTED)

    for server, expected in EXPECTED.items():
        policy = load_policy(outdir / f"{server}.policy.yaml")
        caps = {c.id.value: c for c in policy.caps}
        # deny-by-default is explicit: every policy lists all five classes
        assert set(caps) == ALL_CLASSES, server
        for cap_id, (status, values) in expected.items():
            cap = caps[cap_id]
            assert cap.status.value == status, (server, cap_id, cap.status.value)
            if values is not None:
                assert set(cap.values) == values, (server, cap_id, cap.values)


def test_fleet_infer_denies_by_default_where_no_signal(tmp_path, capsys):
    # The pure-server principle from the demo table: a class with no signal is
    # present-and-denied, never silently granted. Every "denied" cell above
    # must carry no values.
    outdir = tmp_path / "policies"
    assert main(["fleet", "infer", str(MANIFESTS), "-o", str(outdir)]) == 0
    for server, expected in EXPECTED.items():
        policy = load_policy(outdir / f"{server}.policy.yaml")
        for cap in policy.caps:
            if expected[cap.id.value][0] == "denied":
                assert cap.values == [], (server, cap.id.value)
