"""Policy I/O — emit and load policy-mcp-compatible YAML documents.

The emitted base document follows the real Wassette ``policy`` crate schema
(see ``docs/policy-mcp-notes.md``): ``permissions`` carries only the granted
(``inferred``) capabilities in policy-mcp vocabulary, while the
``x-mcp-contract`` extension block preserves the full three-status picture
(statuses, values, evidence, manifest hash). On load, ``x-mcp-contract.caps``
is the source of truth; foreign policy-mcp files without that block are
imported by synthesizing ``inferred`` capabilities from ``permissions``.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from mcp_contract.models import (
    GENERATOR,
    Capability,
    CapabilityId,
    CapabilityStatus,
    Evidence,
    Manifest,
    Policy,
)

POLICY_MCP_SCHEMA = "policy-mcp/v1"
POLICY_MCP_VERSION = "1.0"

_EXT_KEY = "x-mcp-contract"
_FS_SCHEME = "fs://"
_IMPORT_DETAIL = "imported from policy-mcp permissions"


def _granted_values(policy: Policy, cap_id: CapabilityId) -> list[str]:
    cap = policy.granted(cap_id)
    return list(cap.values) if cap is not None else []


def _permissions_block(policy: Policy) -> dict[str, Any]:
    """Build the base policy-mcp ``permissions`` mapping.

    Only INFERRED capabilities with concrete values appear here — this is
    the granted surface a policy-mcp consumer would enforce. proc.exec has
    no policy-mcp analog and never appears (extension block only).
    """
    permissions: dict[str, Any] = {}

    hosts = _granted_values(policy, CapabilityId.NET_HTTP)
    if hosts:
        permissions["network"] = {"allow": [{"host": h} for h in hosts]}

    # Merge fs.read/fs.write grants on the same prefix into one entry.
    access_by_path: dict[str, list[str]] = {}
    for path in _granted_values(policy, CapabilityId.FS_READ):
        access_by_path.setdefault(path, []).append("read")
    for path in _granted_values(policy, CapabilityId.FS_WRITE):
        access = access_by_path.setdefault(path, [])
        if "write" not in access:
            access.append("write")
    if access_by_path:
        permissions["storage"] = {
            "allow": [
                {"uri": _FS_SCHEME + path, "access": access}
                for path, access in access_by_path.items()
            ]
        }

    env_keys = _granted_values(policy, CapabilityId.ENV)
    if env_keys:
        permissions["environment"] = {"allow": [{"key": k} for k in env_keys]}

    return permissions


def policy_to_dict(policy: Policy) -> dict[str, Any]:
    """Serialize a Policy to a policy-mcp-compatible document (plain dict)."""
    return {
        "version": POLICY_MCP_VERSION,
        "description": (
            f"Least-privilege policy for {policy.server_id}, "
            "generated by mcp-contract"
        ),
        "permissions": _permissions_block(policy),
        _EXT_KEY: {
            "schema": POLICY_MCP_SCHEMA,
            "server_id": policy.server_id,
            "source_manifest_hash": policy.manifest_hash,
            "generated_by": policy.generated_by,
            "backend_hint": policy.backend_hint,
            "caps": [c.to_dict() for c in policy.caps],
        },
    }


def dump_policy(policy: Policy, path: str | Path | None = None) -> str:
    """Render a Policy as YAML; also write it to ``path`` if given."""
    text = yaml.safe_dump(policy_to_dict(policy), sort_keys=False)
    if path is not None:
        Path(path).write_text(text, encoding="utf-8")
    return text


def _read_source(source: str | Path | dict) -> tuple[dict[str, Any], Path | None]:
    """Resolve a path / YAML text / dict source to (document, origin path)."""
    if isinstance(source, dict):
        return source, None
    origin: Path | None = None
    if isinstance(source, Path):
        origin = source
        text = source.read_text(encoding="utf-8")
    else:
        # A str is a file path if one exists there, else inline YAML text
        # (so load_policy(dump_policy(p)) round-trips).
        candidate = Path(source)
        try:
            is_file = candidate.is_file()
        except OSError:
            is_file = False
        if is_file:
            origin = candidate
            text = candidate.read_text(encoding="utf-8")
        else:
            text = source
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise ValueError(f"policy source is not valid YAML: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(
            "unrecognized policy source: expected a mapping document, a path "
            "to one, or YAML text of one"
        )
    return data, origin


def _dedupe(values: list[str]) -> list[str]:
    return list(dict.fromkeys(values))


def _storage_uri_to_prefix(uri: str) -> str:
    """Map a policy-mcp storage URI to our path-prefix vocabulary.

    Trailing glob segments are stripped (prefix semantics subsume them);
    a bare ``**``/``*`` collapses to the root prefix.
    """
    path = uri.removeprefix(_FS_SCHEME)
    while path.endswith(("/**", "/*")):
        path = path[: path.rindex("/")]
    if path in ("**", "*", ""):
        path = "/"
    return path


def _import_foreign(data: dict[str, Any], origin: Path | None) -> Policy:
    """Synthesize a Policy from a policy-mcp file without x-mcp-contract."""
    permissions = data.get("permissions") or {}
    if not isinstance(permissions, dict):
        raise ValueError("unrecognized policy document: 'permissions' is not a mapping")

    values: dict[CapabilityId, list[str]] = {cid: [] for cid in CapabilityId}

    for grant in (permissions.get("network") or {}).get("allow") or []:
        # cidr grants are preserved as opaque values (no host-match analog in v0)
        target = grant.get("host") or grant.get("cidr")
        if target:
            values[CapabilityId.NET_HTTP].append(str(target))

    for grant in (permissions.get("storage") or {}).get("allow") or []:
        uri = grant.get("uri")
        access = grant.get("access")
        if not uri or not access:  # direction unknown -> do not guess a grant
            continue
        prefix = _storage_uri_to_prefix(str(uri))
        if "read" in access:
            values[CapabilityId.FS_READ].append(prefix)
        if "write" in access:
            values[CapabilityId.FS_WRITE].append(prefix)

    for grant in (permissions.get("environment") or {}).get("allow") or []:
        key = grant.get("key")
        if key:
            values[CapabilityId.ENV].append(str(key))

    caps: list[Capability] = []
    for cid in CapabilityId:
        vals = _dedupe(values[cid])
        if vals:
            caps.append(
                Capability(
                    id=cid,
                    status=CapabilityStatus.INFERRED,
                    values=vals,
                    evidence=[
                        Evidence(tool="", source="override", detail=_IMPORT_DETAIL)
                    ],
                )
            )
        else:
            caps.append(Capability(id=cid, status=CapabilityStatus.DENIED))

    return Policy(
        server_id=origin.stem if origin is not None else "unknown",
        manifest_hash="",
        caps=caps,
    )


def _load_caps(ext: dict[str, Any]) -> list[Capability]:
    """Validate and build the capability list from an x-mcp-contract block.

    Fails closed on the approval-seam mistakes that would otherwise widen a
    grant: a scalar-string ``values`` (``values: /data``) would be iterated
    character by character and its ``/`` element matches every absolute
    path; a duplicate cap id would be silently resolved first-wins, so an
    appended revocation would be ignored.
    """
    caps_raw = ext.get("caps") or []
    if not isinstance(caps_raw, list):
        raise ValueError(
            f"unrecognized policy document: '{_EXT_KEY}.caps' is not a list"
        )
    caps: list[Capability] = []
    seen: set[CapabilityId] = set()
    for c in caps_raw:
        if not isinstance(c, dict):
            raise ValueError(
                "unrecognized policy document: capability entry is not a "
                f"mapping: {c!r}"
            )
        vals = c.get("values", [])
        if isinstance(vals, str) or not isinstance(vals, list):
            raise ValueError(
                f"capability '{c.get('id', '?')}': 'values' must be a YAML "
                f"list (e.g. values: [/data]), got {type(vals).__name__}: "
                f"{vals!r}"
            )
        cap = Capability.from_dict(c)
        if cap.id in seen:
            raise ValueError(
                "unrecognized policy document: duplicate capability id "
                f"'{cap.id.value}' in {_EXT_KEY}.caps — resolve the intent "
                "explicitly (one entry per class)"
            )
        seen.add(cap.id)
        caps.append(cap)
    return caps


def load_policy(source: str | Path | dict) -> Policy:
    """Load a Policy from a path, YAML text, or already-parsed dict.

    Our own files carry ``x-mcp-contract.caps`` as the source of truth;
    foreign policy-mcp files are imported via their ``permissions`` block
    (grants become ``inferred``, absent classes ``denied``).
    """
    data, origin = _read_source(source)
    ext = data.get(_EXT_KEY)
    if ext is not None:
        if not isinstance(ext, dict):
            raise ValueError(f"unrecognized policy document: '{_EXT_KEY}' is not a mapping")
        default_id = origin.stem if origin is not None else "unknown"
        return Policy(
            server_id=str(ext.get("server_id", default_id)),
            manifest_hash=str(ext.get("source_manifest_hash", "")),
            caps=_load_caps(ext),
            backend_hint=ext.get("backend_hint"),
            generated_by=str(ext.get("generated_by", GENERATOR)),
        )
    if "permissions" not in data and "version" not in data:
        raise ValueError(
            "unrecognized policy document: expected an 'x-mcp-contract' block "
            "or a policy-mcp 'permissions'/'version' key"
        )
    return _import_foreign(data, origin)


def verify_manifest_hash(policy: Policy, manifest: Manifest) -> bool:
    """True iff the policy was generated from exactly this manifest version."""
    return policy.manifest_hash == manifest.hash()
